name: gacha_calculator
description: 가챠 확률 계산기 - React에서 Flutter로 변환된 앱

publish_to: 'none'

version: 0.7.4+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.6
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  fonts:
    - family: D2Coding
      fonts:
        - asset: assets/fonts/D2Coding.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
